<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-TJVM91P" failures="2" tests="2" name="Default test(failed)" time="0.045" errors="0" timestamp="2021-07-18T13:45:44 BST">
  <testcase classname="test.Test19_TestNGRetryFailedDemo" name="test3" time="0.009">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.Test19_TestNGRetryFailedDemo.test3(Test19_TestNGRetryFailedDemo.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="test.Test19_TestNGRetryFailedDemo" name="test2" time="0.002">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at test.Test19_TestNGRetryFailedDemo.test2(Test19_TestNGRetryFailedDemo.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="test.Test19_TestNGRetryFailedDemo" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
